name: "[SparrowStudios] Discord Webhook API CI"

on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/**"
  pull_request:
    branches:
      - "master"
      - "develop"
      - "feature/**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prep Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: NPM Clean Install
        run: npm ci

  deploy:
    runs-on: self-hosted
    needs: build
    if: ${{ github.event_name == 'push' && github.base_ref == 'master' }}

    steps:
      - name: Clone files to production
        run: |
          Copy-Item -Path "$PWD" -Destination "${PRODUCTION_PATH}" -Recurse -Force

      - name: Restart service
        run: |
          C:\nssm\nssm.exe restart "discord-webhook-api"
